### ISSUE TITLE
TypeError in _generate_kedro_command when debugging run in VSCode

### ISSUE THREAD

**Issue by kaemo** [Galileo-Galilei/kedro-mlflow#78]
`TypeError: object of type 'NoneType' has no len()` happens when suggested [VSCode configuration for kedro](https://kedro.readthedocs.io/en/stable/09_development/01_set_up_vscode.html) is used for debugging. The error is due to commandline arguments being `None` when running pipeline directly through `run.py`.

```
Traceback (most recent call last):
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/olszewk2/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/olszewk2/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/olszewk2/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/olszewk2/dev/pyzypad-example/src/pyzypad_example/run.py", line 75, in <module>
    run_package()
  File "/Users/olszewk2/dev/pyzypad-example/src/pyzypad_example/run.py", line 71, in run_package
    project_context.run()
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 725, in run
    run_params=record_data, pipeline=filtered_pipeline, catalog=catalog
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/olszewk2/dev/pyzypad-example/src/kedro-mlflow/kedro_mlflow/framework/hooks/pipeline_hook.py", line 85, in before_pipeline_run
    pipeline_name=run_params["pipeline_name"],
  File "/Users/olszewk2/dev/pyzypad-example/src/kedro-mlflow/kedro_mlflow/framework/hooks/pipeline_hook.py", line 136, in _generate_kedro_command
    if len(from_inputs) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by kaemo** [comment]
I see its fixed now so I'm closing this issue.
